version: "2"
networks:
    # This special network is configured so that the local metadata
    # service can bind to the specific IP address that ECS uses
    # in production
    credentials_network:
        driver: bridge
        ipam:
            config:
                - subnet: "169.254.170.0/24"
                  gateway: 169.254.170.1
services:
    # This container vends credentials to your containers
    ecs-local-endpoints:
        # The Amazon ECS Local Container Endpoints Docker Image
        image: amazon/amazon-ecs-local-container-endpoints
        volumes:
          # Mount /var/run so we can access docker.sock and talk to Docker
          - /var/run:/var/run
          # Mount the shared configuration directory, used by the AWS CLI and AWS SDKs
          # On Windows, this directory can be found at "%UserProfile%\.aws"
          - $HOME/.aws/:/home/.aws/
        environment:
          # define the home folder; credentials will be read from $HOME/.aws
          HOME: "/home"
          # You can change which AWS CLI Profile is used
          AWS_PROFILE: "default"
        networks:
            credentials_network:
                # This special IP address is recognized by the AWS SDKs and AWS CLI 
                ipv4_address: "169.254.170.2"
    dynamodb:
        image: amazon/dynamodb-local
        ports:
            - "8000:8000"   
        depends_on: 
            - ecs-local-endpoints
        networks:
            credentials_network:
                # This special IP address is recognized by the AWS SDKs and AWS CLI 
                ipv4_address: "169.254.170.4"      
    dynamo-admin:
        image: instructure/dynamo-local-admin
        ports:
            - "8001:8001"
            - "8042:8042"
        depends_on: 
            - ecs-local-endpoints
            - dynamodb
        environment:
            DYNAMO_ENDPOINT: http://169.254.170.4:8000      
        networks:
            credentials_network:
                # This special IP address is recognized by the AWS SDKs and AWS CLI 
                ipv4_address: "169.254.170.5"            
    lambda:
        container_name: lambda
        image: lambci/lambda:go1.x
        #command: app.MyFunctionName
        ports: 
            - "9001:9001"
        volumes:
            - ./:/var/task:ro,delegated
        environment: 
            DOCKER_LAMBDA_STAY_OPEN: 1
        depends_on: 
            - ecs-local-endpoints
            - dynamodb
        networks: 
            credentials_network:
                ipv4_address: "169.254.170.6"
    # Here we reference the application container that we are testing
    # You can test multiple containers at a time, simply duplicate this section
    # and customize it for each container, and give it a unique IP in 'credentials_network'.
    app:
        depends_on:
            - ecs-local-endpoints
            - dynamodb
            - lambda
        networks:
            credentials_network:
                ipv4_address: "169.254.170.3"
        environment:
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: "/creds"
          AWS_LAMBDA_SERVER_PORT: "5000"
          AWS_LAMBDA_RUNTIME_API: "169.254.170.6:9001"